#!/usr/bin/env bash
# A script that displays the string "Best School" 10 times using s while loop
# On the 9th iteration it displays "Hi" before "Best School"

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( i++ ))
done
